Linters Setup
Kingobaino1/HTML-Form_Project pull request #1
Opened 2020-08-18 16:24 UTC by Kingobaino1

**In this pull request**
- We setup linters for the HTML form project.

2020-08-19 21:12 UTC, Kingobaino1 commented
**In this project**
- we setup linters
- we cloned the INTUIT signup page

2020-08-19 21:42 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

### Hi team, you guys did a very good job so far!
#### I can see that you guys are working hard at this project, and you're almost done, there are just some required changes* that you guys have to implement in order to proceed:

_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
 
### [REQUIRED CHANGES]
- [ ] Your code is throwing some warnings at the [HTML5 Validator](https://validator.w3.org/nu/#textarear), please fix them.💥
![image](https://user-images.githubusercontent.com/56762529/90690707-909dba00-e248-11ea-81f7-97fc4e2c20eb.png)
- [ ] Guys, next time be aware of some of your commits, they should be descriptive so the other programmer can easily understand what was changed. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
![image](https://user-images.githubusercontent.com/56762529/90694483-11f84b00-e24f-11ea-8c37-4912960cc1a1.png)
![image](https://user-images.githubusercontent.com/56762529/90694524-23d9ee00-e24f-11ea-9903-ff48e25cc610.png)
![image](https://user-images.githubusercontent.com/56762529/90694559-2fc5b000-e24f-11ea-8780-6f0253818efe.png)
(If problem means linter errors, prefer to write like this: Fix linter errors or Fix general linter errors)

- [ ] The type of the phone `<input>` should be `tel `, not text ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png)from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/)) 📞
- [ ] Kindly remove all the unnecessary files (e.g. `package-lock.json`). 🗑
- [ ] Please remove all the unnecessarily repeated CSS code ([Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) Tip: Create one only class like this: .d-flex { display: flex } and use that same class when you need it. 
![image](https://user-images.githubusercontent.com/56762529/90691271-744e4d00-e249-11ea-9e70-9e7d50eaeff0.png)
Explanation: You guys have a lot of repeated code, and it's not a good practice, remember to always keep your code DRY (Don't Repeat Yourself).

- [ ] Improve the title and description of this pull request. Since you guys aren't just setting up the linters, but building a project with forms, semantic HTML, and so on. For more info check [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

### [OPTIONAL CHANGES]

- [ ] To improve UI/UX, add some padding to your inputs

## Summary
- Your code looks clean, and you're using the best HTML and CSS, just have to improve it a bit 👌
- Your repo looks very professional and well organized 🗃
- You both have an attention to details, keep it up! 🔝
- We just have to fix what was pointed above, but it will be easy for you 🔧💪

### But that was close 😅
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif">

### Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

  
<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-19 21:42 UTC, kevincappuccino commented on index.html
> +        <header class="heading">
the `<header>` tag can stay outside of the container
```
<body>
  <header></header>
  <main></main>
  <footer></footer>
</body>
```

2020-08-19 21:42 UTC, kevincappuccino commented on index.html
> +    <div class="container">
You could use the `<main>` tag as the container.

2020-08-19 21:42 UTC, kevincappuccino commented on index.html
> +                            <input id="phone" type="text" name="phone">
- [ ] The type of the phone `<input>` should be `tel`, not text ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png)from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/)) 📞

2020-08-19 22:09 UTC, kevincappuccino commented
> 
> 
> **In this pull request**
> 
>     * We setup linters for the HTML form project.

- [ ] Kindly add more description to this pull request! 😁

2020-08-20 14:49 UTC, abmasadullah commented
## INTUIT signup page ##
**In this project**
- We setup linter to have fast track the linting errors
- We cloned the INTUIT Sign Up page
- We created a form for Sign Up page

2020-08-20 17:34 UTC, kevcap approved these changes
# [STATUS] PROJECT APPROVED 🍾

### I really like your project! Congrats team, you guys did an excellent job!

_**Clean and modular code, following the best practices and the design looks great, keep it up!**_ 🥇

## [OPTIONAL CHANGES]
- [ ] To improve UI/UX, add some padding to your inputs.
- [ ] Replace Author1 and Author2 with your names.

This one should be required, but since it wasn't pointed out earlier 😅, I'll mark it as optional, but I 
strongly suggest that you guys implement it: 
- [ ] Update the project name in your README


## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-08-20 17:34 UTC, kevincappuccino commented on README.md
> +# EMBEDDING IMAGES AND VIDEO
- [ ] Please update the name of this project! ( Project name: HTML Forms )

2020-08-20 17:34 UTC, kevincappuccino commented on README.md
> +👤 **Author2**
- [ ] To make your readme file more professional, you guys can add your names here

2020-08-20 17:34 UTC, kevincappuccino commented on README.md
> +👤 **Author1**
- [ ] To make your readme file more professional, you guys can add your names here

2020-08-20 17:39 UTC, merged